#include <stdio.h>
#include <stdlib.h>
#include <time.h>

void russian(void);
void russian(void) {
    
    srand(time(NULL));

    int number = rand() % 10 + 1;
    int response;
    int attempts = 3;

    for (int num = 0; num < attempts; num++) {
        
        printf("Attempt number : %d out of %d\n", num + 1, attempts);
        printf("Please enter a number generated by the roulette wheel ! : ");
        
        scanf("%d", &response);

        if (response < 1 || response > 10) {
            
            printf("This option is invalid, please choose a number between 1 and 10 !\n");
        
        } 
        
        else if (response == number) {
            
            printf("You have found the number generated by the roulette wheel ! : %d\n", number);
            return;
        
        } 
        
        else {
            
            printf("You did not manage to find the number generated by the roulette wheel !\n");
        
        }
    
    }

    printf("The number was : %d\n", number);

}

int main() {
    
    russian();
    return 0;

}
